module block

// default_block_items is the item form of every modelled block, one entry per
// placeable item. The item registry seeds itself from this list, so a block
// and the item that places it stay defined side by side in this package.
pub fn default_block_items() []BlockItem {
	mut items := []BlockItem{}
	items << new_stone_item()
	items << new_dirt_item()
	items << new_grass_block_item()
	items << new_bedrock_item()
	items << new_coal_ore_item()
	items << new_iron_ore_item()
	items << new_gold_ore_item()
	items << new_diamond_ore_item()
	items << new_emerald_ore_item()
	items << new_copper_ore_item()
	items << new_redstone_ore_item()
	items << new_lapis_ore_item()
	items << new_coal_block_item()
	items << new_iron_block_item()
	items << new_gold_block_item()
	items << new_diamond_block_item()
	items << new_emerald_block_item()
	items << new_copper_block_item()
	items << new_redstone_block_item()
	items << new_lapis_block_item()
	items << new_cobblestone_item()
	items << new_sand_item()
	items << new_red_sand_item()
	items << new_gravel_item()
	items << new_sandstone_item()
	items << new_andesite_item()
	items << new_polished_andesite_item()
	items << new_diorite_item()
	items << new_polished_diorite_item()
	items << new_granite_item()
	items << new_polished_granite_item()
	items << new_netherrack_item()
	items << new_end_stone_item()
	items << new_obsidian_item()
	items << new_ice_item()
	items << new_snow_item()
	items << new_clay_item()
	items << new_mossy_cobblestone_item()
	items << new_packed_ice_item()
	items << new_blue_ice_item()
	items << new_cobbled_deepslate_item()
	items << new_tuff_item()
	items << new_calcite_item()
	items << new_smooth_basalt_item()
	items << new_dripstone_block_item()
	items << new_soul_sand_item()
	items << new_soul_soil_item()
	items << new_glowstone_item()
	items << new_magma_block_item()
	items << new_purpur_block_item()
	items << new_end_bricks_item()

	items << wood_items()
	items << redstone_component_items()
	items << container_items()
	items << farming_items()
	items << combat_progression_items()
	items << decorative_items()

	return items
}
